version: "3.8"
services:
  backend:
    image: "matlabbabaev/springboot-react-fullstack:3.6.2022.3.19.53"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
