version: "3.8"
services:
  backend:
    image: "amigoscode/springboot-react-fullstack:3.6.2022.1.34.3"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
